export enum Repository {
  USERS_REPOSITORY = 'USERS_REPOSITORY',
  PRODUCTS_REPOSITORY = 'PRODUCTS_REPOSITORY',
  ORDER_REPOSITORY = 'ORDER_REPOSITORY',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  DATA_SOURCE = 'DATA_SOURCE',
}
